import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import { auth } from '@/lib/auth';
import { cn } from '@/lib/utils';
import Navigation from '@/components/layouts/navigation';
import { Toaster } from '@/components/ui/toaster';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { getUser } = await auth();
  const user = getUser();
  return (
    <html lang="en">
      <body
        className={cn(
          'min-h-screen bg-neutral-50 flex flex-col space-y-4 flex-1 font-sans text-slate-900 antialiased',
          inter.className
        )}
      >
        <>
          <Navigation user={user} />
          <main className="flex flex-1 p-2 lg:px-20 py-4">{children}</main>
          <Toaster />
        </>
      </body>
    </html>
  );
}
